Add functional task to install Pangeo helm chart and config templates
cedadev/pangeo-helm-ansible pull request #1
Opened 2019-03-06 17:17 UTC by brtknr

2019-03-14 11:36 UTC, brtknr commented on tasks/main.yml
> +    src: secret_config.yaml.j2
chmod 600

2019-03-14 11:37 UTC, brtknr commented on templates/jupyter_config.yaml.j2
> +      GCSFUSE_BUCKET: pangeo-data
remove

2019-03-14 11:37 UTC, brtknr commented on templates/jupyter_config.yaml.j2
> +      EXTRA_PIP_PACKAGES: >-
remove

2019-03-14 11:41 UTC, brtknr commented on templates/secret_config.yaml.j2
> +    secretToken: 8ab358498cadf3e05db75341c3ba9b41d65e565433a6ec17020afe31f2dd7806
use ansible_facts, look at awx

2019-03-14 11:41 UTC, brtknr commented on templates/secret_config.yaml.j2
> +    secretToken: 8ab358498cadf3e05db75341c3ba9b41d65e565433a6ec17020afe31f2dd7806
rabbitmq

2019-03-20 10:49 UTC, oneswig commented on tasks/main.yml
> +  template:
Set a mode, eg 0600, in particular secret_config looks a bit sensitive?

2019-03-20 10:50 UTC, oneswig reviewed
What's with the secret token committed?

2019-03-21 09:40 UTC, mkjpryor-stfc requested changes
Looks pretty good. I just have one comment really.

The `pangeo_upgrade` flag is not required - according to the playbook compatibility document, Pangeo should be upgraded if a different `pangeo_version` is specified to the installed version. I think this would also allow you to get away with a single `helm upgrade --install` task handling initial installation and upgrading.

(If you look at this PR - https://github.com/cedadev/k8s-ansible/pull/7 - it actually removes the `upgrade_kubernetes` flag from `k8s-ansible` and replaces it with a check whether the requested version matches the currently installed one.

2019-03-22 11:09 UTC, brtknr commented
Thanks for the feedback @mkjpryor-stfc , I have addressed your feedback :)

2019-03-25 10:07 UTC, mkjpryor-stfc requested changes
Other than that, looks good.

2019-03-25 10:07 UTC, mkjpryor-stfc commented on tasks/main.yml
> +    current_release: "{{ ({} if output.stdout == '' else (output.stdout | from_json)).get('Releases', [{}]) | first }}"
Could this be made cleaner with the `json_query` filter?

https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#json-query-filter

2019-03-25 11:33 UTC, merged